apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: antwort-frontend
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: antwort-frontend
    weight: 100
  port:
    targetPort: http
