#!/usr/bin/env bash
# Generate markdown report from cluster validation results JSON
# Usage: test/cluster/report.sh <results.json>
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RESULTS_DIR="$SCRIPT_DIR/results"

if [ $# -lt 1 ]; then
    echo "Usage: $0 <results.json>"
    exit 1
fi

INPUT_JSON="$1"
if [ ! -f "$INPUT_JSON" ]; then
    echo "ERROR: Results file not found: $INPUT_JSON"
    exit 1
fi

# Extract fields from JSON
MODEL=$(jq -r '.model' "$INPUT_JSON")
VERSION=$(jq -r '.antwort_version' "$INPUT_JSON")
TIMESTAMP=$(jq -r '.timestamp' "$INPUT_JSON")
TOTAL_PASSED=$(jq -r '.total_passed' "$INPUT_JSON")
TOTAL_TESTS=$(jq -r '.total_tests' "$INPUT_JSON")

# Generate filename
DATE_PART=$(echo "$TIMESTAMP" | cut -d'T' -f1)
MODEL_SAFE=$(echo "$MODEL" | tr '/' '_' | tr ' ' '_')
REPORT_FILE="${RESULTS_DIR}/${DATE_PART}_${MODEL_SAFE}.md"

# Generate markdown report
cat > "$REPORT_FILE" << REPORT_EOF
# Validation Results: ${MODEL}

**Date**: ${TIMESTAMP}
**Antwort Version**: ${VERSION}
**Overall**: ${TOTAL_PASSED}/${TOTAL_TESTS} tests passed

## Category Scores

| Category | Passed | Total | Score |
|----------|--------|-------|-------|
REPORT_EOF

# Add category rows
jq -r '.categories | to_entries[] | "| \(.key) | \(.value.passed) | \(.value.total) | \((.value.score * 100) | floor)% |"' "$INPUT_JSON" >> "$REPORT_FILE"

# Add overall row
if [ "$TOTAL_TESTS" -gt 0 ]; then
    OVERALL_PCT=$(echo "scale=0; $TOTAL_PASSED * 100 / $TOTAL_TESTS" | bc)
else
    OVERALL_PCT=0
fi
echo "| **Overall** | **${TOTAL_PASSED}** | **${TOTAL_TESTS}** | **${OVERALL_PCT}%** |" >> "$REPORT_FILE"

# Add latency section
cat >> "$REPORT_FILE" << 'LATENCY_HEADER'

## Latency

| Metric | P50 | P95 | P99 |
|--------|-----|-----|-----|
LATENCY_HEADER

NS_P50=$(jq -r '.latency.non_streaming_p50_ms // 0 | floor' "$INPUT_JSON")
NS_P95=$(jq -r '.latency.non_streaming_p95_ms // 0 | floor' "$INPUT_JSON")
NS_P99=$(jq -r '.latency.non_streaming_p99_ms // 0 | floor' "$INPUT_JSON")
echo "| Non-streaming | ${NS_P50}ms | ${NS_P95}ms | ${NS_P99}ms |" >> "$REPORT_FILE"

ST_P50=$(jq -r '.latency.streaming_ttft_p50_ms // 0 | floor' "$INPUT_JSON")
ST_P95=$(jq -r '.latency.streaming_ttft_p95_ms // 0 | floor' "$INPUT_JSON")
ST_P99=$(jq -r '.latency.streaming_ttft_p99_ms // 0 | floor' "$INPUT_JSON")
echo "| Streaming TTFT | ${ST_P50}ms | ${ST_P95}ms | ${ST_P99}ms |" >> "$REPORT_FILE"

# Add failures section if any
FAILURE_COUNT=$(jq '.failures | length' "$INPUT_JSON")
if [ "$FAILURE_COUNT" -gt 0 ]; then
    echo "" >> "$REPORT_FILE"
    echo "## Failures" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    jq -r '.failures[] | "### \(.test_name)\n- **Category**: \(.category)\n- **Error**: \(.error)\n"' "$INPUT_JSON" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Generated by antwort cluster validation harness*" >> "$REPORT_FILE"

# Update latest symlink
ln -sf "$(basename "$REPORT_FILE")" "${RESULTS_DIR}/latest.md"

# Write latest.json for docs site
cp "$INPUT_JSON" "${RESULTS_DIR}/latest.json"

echo "Report written to: $REPORT_FILE"
echo "latest.md -> $(basename "$REPORT_FILE")"
echo "latest.json updated"
