apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-backend
  labels:
    app.kubernetes.io/name: mock-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mock-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mock-backend
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mock-backend
          image: mock-backend:ci
          imagePullPolicy: Never
          env:
            - name: MOCK_PORT
              value: "9090"
          ports:
            - name: http
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: mock-backend
spec:
  selector:
    app.kubernetes.io/name: mock-backend
  ports:
    - name: http
      port: 9090
      targetPort: http
