apiVersion: v1
kind: Service
metadata:
  name: antwort-backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: antwort-backend
